apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    dexOptions {
        javaMaxHeapSize "5g"
        jumboMode = true
    }
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.packag.ezeety"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
    buildToolsVersion = '28.0.3'
    buildscript {
        repositories {
            jcenter()
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //noinspection GradleCompatible
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.1.0'
    implementation 'com.google.firebase:firebase-auth:19.1.0'
    testImplementation 'junit:junit:4.12'
    //noinspection GradleCompatible
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.j256.ormlite:ormlite-android:5.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    //noinspection GradleCompatible
    implementation 'androidx.cardview:cardview:1.0.0'
    //noinspection GradleCompatible
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'com.facebook.android:facebook-login:[5,6)'
    implementation 'de.hdodenhof:circleimageview:3.0.1'
    //noinspection GradleCompatible
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.github.bumptech.glide:glide:4.6.1'
    implementation 'org.greenrobot:eventbus:3.1.1'
}
